MODEL:
  DROP_PATH_RATE: 0.2
  EMBED_DIM: 1024
  HIDDEN_DIM2: 512
  NAME: swin_small_patch4_window7_224
TRAIN:
  BASE_LR: 1.0e-06
  BATCH_SIZE: 4
  DISTRIBUTED: False
  EPOCHS: 100
  GRAD_ACCUM: 1
  MIN_LR: 2.0e-07
  NUM_CLASSES: 2
  NUM_WORKERS: 12
  PATIENCE: 30
  STEPS_PER_EPOCH: 128
  VALID_BATCH_SIZE: 1
  WARMUP_EPOCHS: 5
  WARMUP_LR: 2.0e-08
  WEIGHT_DECAY: 5.0e-05
